export function getMockData() {
  return {
    recommendedPartners: [
      {
        id: 'partner-1',
        name: 'Rishwanth',
        profilePicture: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        bio: 'UI/UX designer with 5 years of experience. Love to share design knowledge!',
        skills: ['Figma', 'UI/UX Design', 'Adobe XD'],
        rating: 4.9,
        matchScore: 95,
      },
      {
        id: 'partner-2',
        name: 'Lalasa',
        profilePicture: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
        bio: 'Graphic designer interested in learning web development',
        skills: ['Photoshop', 'Illustrator', 'Branding'],
        rating: 4.7,
        matchScore: 88,
      },
      {
        id: 'partner-3',
        name: 'Taqib Aza',
        profilePicture: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
        bio: 'Product designer wanting to learn React and frontend development',
        skills: ['Product Design', 'User Research', 'Wireframing'],
        rating: 4.8,
        matchScore: 92,
      },
      {
        id: 'partner-4',
        name: 'Emily Watson',
        profilePicture: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400',
        bio: 'Marketing specialist learning Python for data analysis',
        skills: ['Digital Marketing', 'SEO', 'Content Strategy'],
        rating: 4.6,
        matchScore: 82,
      },
    ],
    activeExchanges: [
      {
        id: 'exchange-1',
        partnerId: 'partner-1',
        partnerName: 'Rishwanth',
        partnerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        yourSkill: 'React',
        theirSkill: 'UI/UX Design',
        nextSession: 'Tomorrow, 3:00 PM',
      },
      {
        id: 'exchange-2',
        partnerId: 'partner-2',
        partnerName: 'Lalasa',
        partnerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
        yourSkill: 'Node.js',
        theirSkill: 'Graphic Design',
        nextSession: 'Friday, 2:00 PM',
      },
    ],
    pendingRequests: [
      {
        id: 'request-1',
        name: 'Taqib Aza',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
        message: 'Would love to learn React from you!',
        skill: 'React ↔ Product Design',
      },
    ],
    completedExchanges: 18,
    allUsers: [
      {
        id: 'partner-1',
        name: 'Rishwanth',
        profilePicture: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        bio: 'UI/UX designer with 5 years of experience. Love to share design knowledge!',
        skillsToTeach: ['Figma', 'UI/UX Design', 'Adobe XD', 'User Research'],
        skillsToLearn: ['React', 'Frontend Development'],
        rating: 4.9,
        reviewCount: 45,
        credits: 78,
        verified: true,
      },
      {
        id: 'partner-2',
        name: 'Lalasa',
        profilePicture: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
        bio: 'Graphic designer interested in learning web development',
        skillsToTeach: ['Photoshop', 'Illustrator', 'Branding', 'Logo Design'],
        skillsToLearn: ['HTML/CSS', 'JavaScript', 'Node.js'],
        rating: 4.7,
        reviewCount: 32,
        credits: 52,
        verified: true,
      },
      {
        id: 'partner-3',
        name: 'Taqib Aza',
        profilePicture: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
        bio: 'Product designer wanting to learn React and frontend development',
        skillsToTeach: ['Product Design', 'User Research', 'Wireframing', 'Prototyping'],
        skillsToLearn: ['React', 'TypeScript'],
        rating: 4.8,
        reviewCount: 38,
        credits: 65,
        verified: true,
      },
      {
        id: 'partner-4',
        name: 'James Wilson',
        profilePicture: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
        bio: 'Business analyst looking to improve presentation skills',
        skillsToTeach: ['Excel', 'Data Visualization', 'Business Analytics'],
        skillsToLearn: ['Public Speaking', 'PowerPoint Design'],
        rating: 4.5,
        reviewCount: 22,
        credits: 38,
        verified: true,
      },
      {
        id: 'partner-5',
        name: 'Sophia Martinez',
        profilePicture: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400',
        bio: 'Software engineer teaching advanced programming concepts',
        skillsToTeach: ['Java', 'Spring Boot', 'Microservices'],
        skillsToLearn: ['Machine Learning', 'AI'],
        rating: 4.8,
        reviewCount: 42,
        credits: 68,
        verified: true,
      },
      {
        id: 'partner-6',
        name: 'Nina Patel',
        profilePicture: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
        bio: 'Professional photographer teaching composition and lighting',
        skillsToTeach: ['Photography', 'Photo Editing', 'Lightroom', 'Composition'],
        skillsToLearn: ['Video Editing', 'Motion Graphics'],
        rating: 4.9,
        reviewCount: 56,
        credits: 92,
        verified: true,
      },
    ],
    skills: [
      { id: 's1', name: 'React', category: 'Programming', count: 145 },
      { id: 's2', name: 'Python', category: 'Programming', count: 132 },
      { id: 's3', name: 'JavaScript', category: 'Programming', count: 156 },
      { id: 's4', name: 'UI/UX Design', category: 'Design', count: 98 },
      { id: 's5', name: 'Figma', category: 'Design', count: 87 },
      { id: 's6', name: 'Spanish', category: 'Languages', count: 76 },
      { id: 's7', name: 'French', category: 'Languages', count: 64 },
      { id: 's8', name: 'Digital Marketing', category: 'Marketing', count: 91 },
      { id: 's9', name: 'SEO', category: 'Marketing', count: 72 },
      { id: 's10', name: 'Guitar', category: 'Music', count: 43 },
      { id: 's11', name: 'Piano', category: 'Music', count: 38 },
      { id: 's12', name: 'Photography', category: 'Photography', count: 67 },
      { id: 's13', name: 'Photo Editing', category: 'Photography', count: 58 },
      { id: 's14', name: 'Business Strategy', category: 'Business', count: 54 },
      { id: 's15', name: 'Data Science', category: 'Data Science', count: 82 },
    ],
    certifications: [
      {
        id: 'cert-1',
        userId: 'user-1',
        userName: 'Lalasa',
        skillName: 'React',
        documentUrl: '#',
        status: 'pending',
        uploadedDate: '2026-03-05',
      },
      {
        id: 'cert-2',
        userId: 'user-2',
        userName: 'Rishwanth',
        skillName: 'Python',
        documentUrl: '#',
        status: 'pending',
        uploadedDate: '2026-03-06',
      },
      {
        id: 'cert-3',
        userId: 'user-3',
        userName: 'Taqib Aza',
        skillName: 'UI/UX Design',
        documentUrl: '#',
        status: 'pending',
        uploadedDate: '2026-03-07',
      },
    ],
  };
}